"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
var gql = require("apollo-server").gql;
var types = gql(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  type User {\n    _id: ID\n    name: String\n    userName: String\n    email: String\n    friends: [String]\n  }\n\n  type LoggedUser {\n    _id: ID\n    name: String\n    userName: String\n    email: String\n    token: String\n    friends: [String]\n  }\n\n  type UserAndTweets {\n    user: User\n    tweets: [Tweet]\n  }\n\n  extend type Query {\n    getUsers: [User]\n    getUserById(_id: String!): UserAndTweets\n    validateToken(token: String!): Boolean\n  }\n\n  extend type Mutation {\n    addToFriends(_id: String!, newFriendId: String!, token: String!): LoggedUser\n    removeFromFriends(\n      _id: String!\n      friendId: String!\n      token: String!\n    ): LoggedUser\n    login(email: String, password: String): LoggedUser\n    saveUser(\n      userName: String!\n      name: String!\n      email: String!\n      password: String!\n    ): LoggedUser\n  }\n"], ["\n  type User {\n    _id: ID\n    name: String\n    userName: String\n    email: String\n    friends: [String]\n  }\n\n  type LoggedUser {\n    _id: ID\n    name: String\n    userName: String\n    email: String\n    token: String\n    friends: [String]\n  }\n\n  type UserAndTweets {\n    user: User\n    tweets: [Tweet]\n  }\n\n  extend type Query {\n    getUsers: [User]\n    getUserById(_id: String!): UserAndTweets\n    validateToken(token: String!): Boolean\n  }\n\n  extend type Mutation {\n    addToFriends(_id: String!, newFriendId: String!, token: String!): LoggedUser\n    removeFromFriends(\n      _id: String!\n      friendId: String!\n      token: String!\n    ): LoggedUser\n    login(email: String, password: String): LoggedUser\n    saveUser(\n      userName: String!\n      name: String!\n      email: String!\n      password: String!\n    ): LoggedUser\n  }\n"])));
module.exports = { types: types };
var templateObject_1;
